---
- hosts: webserver
  become: true
  tasks:
  - name: install apache2
    yum:
      name: httpd
      update_cache: yes
      state: present
  - name: copy the file
    copy:
       src: index.html
       dest: /var/www/html/index.html
